version: '3'
services:
  task-redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"

  #Run tests in Docker `docker-compose up` on Node.js v4
  #- install node deps first `docker-compose run agenda npm install`
  task-scheduler:
    #build: .
    image: node:10.4.0-jessie
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    environment:
      - REDIS_HOST=task-redis
      - HTTP_AUTH_MODE=basic
      - AUTH_USER_NAME=${AUTH_USER_NAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    links:
      - task-redis
